// Copyright (c) 2026. All rights reserved.

/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6309be33e29e063db8114233079af21c)
interface __BaseEnv_Env {
	SESSIONS: KVNamespace;
	AUTH_RATE_LIMITER: RateLimit;
	ALLOWED_ORIGINS: "https://sclife2003.github.io";
	GITHUB_DATA_OWNER: "sclife2003";
	GITHUB_DATA_REPO: "xueba-pvz-data";
	GITHUB_DATA_BRANCH: "main";
	GITHUB_TOKEN: string;
	PASSWORD_PEPPER: string;
	PASSWORD_HASHER: DurableObjectNamespace<import("./src/entrypoint").PasswordHasher>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/entrypoint");
		durableNamespaces: "PasswordHasher";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "GITHUB_DATA_OWNER" | "GITHUB_DATA_REPO" | "GITHUB_DATA_BRANCH" | "GITHUB_TOKEN" | "PASSWORD_PEPPER">> {}
}
